package com.carddemo.card;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.LocalDate;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

/**
 * JPA entity for table {@code card}. Card record (CARDDATA KSDS, key CARD-NUM; CARDAIX on CARD-ACCT-ID); browsed by
 * COCRDLIC, read by COCRDSLC, rewritten by COCRDUPC. Field Javadocs carry the CVACT02Y item names; {@link
 * CardRecord} is the fixed-width value.
 */
@Entity
@Table(name = "card")
public class Card {

    /** CARD-NUM PIC X(16). */
    @Id
    @Column(name = "card_num")
    private String cardNum;

    /** CARD-ACCT-ID PIC 9(11). */
    @Column(name = "acct_id")
    private long acctId;

    /** CARD-CVV-CD PIC 9(03). */
    @Column(name = "cvv_cd")
    private int cvvCd;

    /** CARD-EMBOSSED-NAME PIC X(50). */
    @Column(name = "embossed_name")
    private String embossedName;

    /** CARD-EXPIRAION-DATE PIC X(10). */
    @Column(name = "expiration_date")
    private String expirationDate;

    /** {@code expiration_date_dt}: CARD-EXPIRAION-DATE as a DATE, generated by the database. */
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "expiration_date_dt", insertable = false, updatable = false)
    private LocalDate expirationDateDt;

    /** CARD-ACTIVE-STATUS PIC X(01). */
    @Column(name = "active_status")
    private CardStatus activeStatus;

    /** Optimistic-lock version (ADR-0010); not part of the VSAM record. */
    @Version
    @Column(name = "version")
    private long version;

    protected Card() {
    }

    public static Card from(CardRecord record) {
        Card entity = new Card();
        entity.cardNum = record.cardNum();
        entity.acctId = record.acctId();
        entity.cvvCd = record.cvvCd();
        entity.embossedName = record.embossedName();
        entity.expirationDate = record.expirationDate();
        entity.activeStatus = record.activeStatus();
        return entity;
    }

    public CardRecord toRecord() {
        return new CardRecord(cardNum, acctId, cvvCd, embossedName, expirationDate, activeStatus);
    }

    /** {@code REWRITE}: replaces every non-key field with the values of {@code record}; the key must match. */
    public void update(CardRecord record) {
        if (!cardNum.equals(record.cardNum())) {
            throw new IllegalArgumentException("card: cannot change the key of " + cardNum + " via update");
        }
        this.acctId = record.acctId();
        this.cvvCd = record.cvvCd();
        this.embossedName = record.embossedName();
        this.expirationDate = record.expirationDate();
        this.activeStatus = record.activeStatus();
    }

    public String getCardNum() {
        return cardNum;
    }

    public long getAcctId() {
        return acctId;
    }

    public int getCvvCd() {
        return cvvCd;
    }

    public String getEmbossedName() {
        return embossedName;
    }

    public String getExpirationDate() {
        return expirationDate;
    }

    /** CARD-EXPIRAION-DATE parsed by {@code cobol_iso_date}; read-only, the text is the source of truth. */
    public LocalDate getExpirationDateDt() {
        return expirationDateDt;
    }

    public CardStatus getActiveStatus() {
        return activeStatus;
    }

    public long getVersion() {
        return version;
    }
}
