package com.carddemo.batch.creastmt;

import static org.assertj.core.api.Assertions.assertThat;

import com.carddemo.batch.harness.ReturnCode;
import com.carddemo.batch.harness.Sysout;
import com.carddemo.batch.print.PrintProgramsBaselineTest;
import com.carddemo.common.AbendException;
import com.carddemo.common.codec.FixedWidthRecord;
import com.carddemo.common.codec.TestData;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * CBSTM03A on synthetic inputs, compared with what the GnuCOBOL build of CBSTM03A wrote for the same inputs
 * ({@code src/test/resources/creastmt/<case>}, generated by {@code scripts/batch/gen_creastmt_edge_cases.py}).
 */
class Cbstm03aEdgeCaseTest {

    static final String ZERO_TOTAL = "Total EXP:" + " ".repeat(56) + "$" + " ".repeat(9) + ".00 ";

    @TempDir
    Path dir;

    record Outcome(List<String> stmt, List<String> html, List<String> sysout, Cbstm03a.Result result,
                   Throwable abend) {
    }

    static Path fixture(String name, String file) {
        return TestData.resolve("modernization/carddemo-app/src/test/resources/creastmt/" + name + "/" + file);
    }

    static List<String> lines(String name, String file) throws IOException {
        return Files.readAllLines(fixture(name, file), StandardCharsets.ISO_8859_1);
    }

    Outcome run(List<FixedWidthRecord> trnx, Path xref) throws IOException {
        Path sysoutPath = dir.resolve("sysout-" + System.nanoTime() + ".txt");
        CreastmtTestSupport.Run run;
        Cbstm03a.Result result = null;
        Throwable abend = null;
        try (Sysout sysout = Sysout.open(sysoutPath)) {
            run = CreastmtTestSupport.program(() -> trnx, xref, sysout);
            try {
                result = run.program().run();
            } catch (AbendException e) {
                abend = e;
            }
        }
        return new Outcome(run.stmtLines(), run.htmlLines(), PrintProgramsBaselineTest.sysoutLines(sysoutPath),
                result, abend);
    }

    Outcome runFixture(String name) throws IOException {
        return run(CreastmtTestSupport.trnxLines(lines(name, "TRXFL.txt")), fixture(name, "XREF.txt"));
    }

    /** The legacy SYSOUT without the build-time TIOT patch's suffix (the Java program DISPLAYs job and step). */
    static List<String> legacySysout(String name) throws IOException {
        return lines(name, "sysout.txt").stream()
                .map(l -> l.replace("CREASTMT  Step STEP040 (TIOT walk bypassed under GnuCOBOL)",
                        "CREASTMT Step STEP040"))
                .filter(l -> !l.startsWith("CEE3ABD:"))
                .toList();
    }

    @Test
    void cardsWithoutTransactionsGetAnEmptyStatementWithAZeroTotal() throws IOException {
        Outcome out = runFixture("no-transactions");
        assertThat(out.abend()).isNull();
        assertThat(out.result().returnCode()).isEqualTo(ReturnCode.OK);
        assertThat(out.stmt()).containsExactlyElementsOf(lines("no-transactions", "STMTFILE.txt"));
        assertThat(out.html()).containsExactlyElementsOf(lines("no-transactions", "HTMLFILE.txt"));
        assertThat(out.sysout()).containsExactlyElementsOf(legacySysout("no-transactions"));
        assertThat(out.result().statements()).isEqualTo(5);
        // below every TRXFL card, between the two cards, above every TRXFL card: header row, then the total
        assertThat(out.stmt()).filteredOn(ZERO_TOTAL::equals).hasSize(3);
        List<List<String>> statements = new ArrayList<>();
        List<String> current = new ArrayList<>();
        for (String line : out.stmt()) {
            current.add(line);
            if (line.equals(Cbstm03a.ST_LINE15)) {
                statements.add(current);
                current = new ArrayList<>();
            }
        }
        assertThat(current).isEmpty();
        assertThat(statements).hasSize(5);
        assertThat(statements).filteredOn(st -> st.contains(ZERO_TOTAL))
                .hasSize(3).allSatisfy(st -> assertThat(st).hasSize(19));
    }

    @Test
    void moreThanTenTransactionsOverlayTheNextCardLikeTheLegacyProgram() throws IOException {
        Outcome out = runFixture("overflow");
        assertThat(out.abend()).isNull();
        assertThat(out.stmt()).containsExactlyElementsOf(lines("overflow", "STMTFILE.txt"));
        assertThat(out.html()).containsExactlyElementsOf(lines("overflow", "HTMLFILE.txt"));
        assertThat(out.sysout()).containsExactlyElementsOf(legacySysout("overflow"));
        List<String> trxfl = lines("overflow", "TRXFL.txt");
        String nextCard = trxfl.get(12).substring(0, 16);
        // the first card prints 12 lines; lines 11 and 12 are the next card's slot read back as transactions
        assertThat(out.stmt()).filteredOn(l -> l.startsWith(nextCard + " 01")).hasSize(1);
        assertThat(out.stmt().get(26)).startsWith(nextCard);
        assertThat(out.stmt().get(27)).startsWith(" ".repeat(17));
        assertThat(out.result().transactions()).isEqualTo(12 + 0 + 7);
    }

    @Test
    void anEmptyTrxflAbendsOnTheFirstRead() throws IOException {
        assertThat(lines("empty", "rc.txt")).containsExactly("16");
        Outcome out = runFixture("empty");
        assertThat(out.abend()).isInstanceOf(AbendException.class);
        assertThat(out.stmt()).isEmpty();
        assertThat(out.html()).isEmpty();
        assertThat(out.sysout()).containsExactlyElementsOf(legacySysout("empty"));
    }

    @Test
    void anEntryOutsideTheTableAbendsInsteadOfOverwritingOtherStorage() throws IOException {
        List<FixedWidthRecord> trxfl = CreastmtTestSupport.trnxLines(lines("overflow", "TRXFL.txt"));
        byte[] template = trxfl.get(0).bytes();
        List<FixedWidthRecord> cards = new ArrayList<>();
        for (int card = 1; card <= Cbstm03a.MAX_CARDS + 1; card++) {
            byte[] image = template.clone();
            System.arraycopy(String.format("%016d", card).getBytes(StandardCharsets.US_ASCII), 0, image, 0, 16);
            cards.add(new FixedWidthRecord(Cbstm03a.TRNX_LAYOUT, image, CreastmtTestSupport.ASCII));
        }
        Outcome tooManyCards = run(cards, fixture("overflow", "XREF.txt"));
        assertThat(tooManyCards.abend()).hasMessageContaining("WS-TRNX-TABLE OVERFLOW: CARD 52 TRANSACTION 1");
        assertThat(tooManyCards.sysout()).contains("ABENDING PROGRAM");

        List<FixedWidthRecord> lastCard = new ArrayList<>(cards.subList(0, Cbstm03a.MAX_CARDS));
        for (int tran = 2; tran <= Cbstm03a.MAX_TRANSACTIONS + 1; tran++) {
            byte[] image = lastCard.get(Cbstm03a.MAX_CARDS - 1).bytes().clone();
            System.arraycopy(String.format("%016d", tran).getBytes(StandardCharsets.US_ASCII), 0, image, 16, 16);
            lastCard.add(new FixedWidthRecord(Cbstm03a.TRNX_LAYOUT, image, CreastmtTestSupport.ASCII));
        }
        Outcome lastSlotOverflow = run(lastCard, fixture("overflow", "XREF.txt"));
        assertThat(lastSlotOverflow.abend()).hasMessageContaining("CARD 51 TRANSACTION 11");
    }
}
