#!/usr/bin/env bash
# Card list / view / update curl transcript against a running `docker compose up -d --build --wait` stack.
# Usage: scripts/online/card_curl_transcript.sh [base-url] > docs/validation/online/card-list-view-update-curl.md
# Tokens are redacted; list rows carry masked card numbers and opaque cardRef values (ADR-0020).
set -euo pipefail
BASE=${1:-http://localhost:${CARDDEMO_HTTP_PORT:-8080}}
API=$BASE/api/v1
BODY=$(mktemp)
trap 'rm -f "$BODY"' EXIT

# step <title> <curl args...>: prints the request (bearer redacted), status and pretty JSON; leaves the body in $BODY
step() {
  local title=$1; shift
  local shown=()
  for a in "$@"; do
    case $a in
      "Authorization: Bearer "*) shown+=("'Authorization: Bearer \$TOKEN'") ;;
      *[[:space:]\"{}?]*) shown+=("'$a'") ;;
      *) shown+=("$a") ;;
    esac
  done
  printf '### %s\n$ curl %s\n' "$title" "${shown[*]}"
  local code
  code=$(curl -s -o "$BODY" -w '%{http_code}' "$@")
  printf 'HTTP %s\n' "$code"
  jq '(.. | objects | select(has("token")) | .token) |= "<redacted>"' "$BODY" 2>/dev/null || cat "$BODY"
  printf '\n'
}

login() {
  curl -s "$API/auth/login" -H 'Content-Type: application/json' -d "{\"userId\":\"$1\",\"password\":\"PASSWORD\"}" \
    | jq -r .token
}

cat <<HDR
# Card list / view / update — curl transcript (docker compose)

Generated by \`scripts/online/card_curl_transcript.sh\` against \`docker compose up -d --build --wait\` (local profile,
initial load of \`app/data/EBCDIC\`, fresh volume) on branch \`devin/unt51-19-card-list-view-update\`; tokens redacted.
List rows show masked card numbers and opaque \`cardRef\` cursors (ADR-0020); the single-card screens show the full
number as CCRDSLA/CCRDUPA do. Steps: sign-on (ADMIN001, USER0001), ADMIN list first/next/previous page (7 rows, baseline
order), account filter, USER without account (403) / with account / other account's card (404), row selection,
detail by reference, account path, PUT edit error (400), ENTER (\`confirm=false\`), PF5 (\`confirm=true\`), stale
version (409), re-read.

\`\`\`text
HDR

step "Sign on as ADMIN001 (type A)" "$API/auth/login" -H 'Content-Type: application/json' \
  -d '{"userId":"ADMIN001","password":"PASSWORD"}'
ADMIN=$(login ADMIN001)
USER=$(login USER0001)
AA="Authorization: Bearer $ADMIN"
UA="Authorization: Bearer $USER"

step "ADMIN: first page (no filter: all cards, 7 rows in card-number order)" "$API/cards" -H "$AA"
NEXT=$(jq -r .nextPage "$BODY")
step "ADMIN: PF8 next page (after = last row's cardRef)" "$API/cards?after=$NEXT" -H "$AA"
PREV=$(jq -r .previousPage "$BODY")
step "ADMIN: PF7 previous page (before = first row's cardRef) - back to page 1" "$API/cards?before=$PREV" -H "$AA"
step "ADMIN: account filter 27" "$API/cards?accountId=27" -H "$AA"
step "ADMIN: filter matching nothing (account 99)" "$API/cards?accountId=99" -H "$AA"
step "ADMIN: invalid account filter -> 400" "$API/cards?accountId=12A" -H "$AA"

step "Sign on as USER0001 (type U)" "$API/auth/login" -H 'Content-Type: application/json' \
  -d '{"userId":"USER0001","password":"PASSWORD"}'
step "USER: list without an account in context -> 403 NOTAUTH" "$API/cards" -H "$UA"
step "USER: list restricted to account 50" "$API/cards?accountId=50" -H "$UA"
REF=$(jq -r '.rows[0].cardRef' "$BODY")
step "USER: card of another account (card of account 50 with account 27 in context) -> 404" \
  "$API/cards/0500024453765740?accountId=27" -H "$UA"
step "USER: select row 1 with S (XCTL to COCRDSLC)" -X POST "$API/cards/selection" -H "$UA" \
  -H 'Content-Type: application/json' -d "{\"accountId\":\"00000000050\",\"rows\":[{\"cardRef\":\"$REF\",\"action\":\"S\"}]}"
step "USER: card detail by reference (COCRDSLC, full card number)" \
  "$API/cards/$REF?accountId=00000000050&fromProgram=COCRDLIC" -H "$UA"
step "USER: account path (CARDAIX) for account 27" "$API/cards/by-account/27" -H "$UA"
step "USER: card detail of 0683586198171516 for update" "$API/cards/0683586198171516?accountId=27" -H "$UA"
FORM=$(jq -c .updateForm "$BODY")

put() {
  step "$1" -X PUT "$API/cards/0683586198171516" -H "$UA" -H 'Content-Type: application/json' -d "$2"
}
put "USER: PUT name with a digit -> 400" "$(jq -c '.embossedName = "Ward J0nes"' <<<"$FORM")"
put "USER: PUT month 13 and year 1949 -> 400 (first error reported, all fields flagged)" \
  "$(jq -c '.expiryMonth = "13" | .expiryYear = "1949"' <<<"$FORM")"
put "USER: PUT unchanged (upper/trim) -> no change" "$(jq -c '.embossedName = " ward jones "' <<<"$FORM")"
CHANGED=$(jq -c '.embossedName = "Ward B Jones" | .expiryMonth = "12" | .expiryYear = "2029"' <<<"$FORM")
put "USER: ENTER (confirm=false) -> VALIDATED, nothing written" "$CHANGED"
put "USER: PF5 (confirm=true) -> COMMITTED, version 0 -> 1" "$(jq -c '.confirm = true' <<<"$CHANGED")"
put "USER: PF5 again with the stale version 0 -> 409 CHANGED" \
  "$(jq -c '.confirm = true | .activeStatus = "N"' <<<"$CHANGED")"
step "USER: re-read (committed values, version 1)" "$API/cards/0683586198171516?accountId=27" -H "$UA"

printf '```\n'
