#!/usr/bin/env bash
# Transaction list / view / add and bill payment curl transcript against a running
# `docker compose up -d --build --wait` stack (fresh volume: TRANSACT is empty after initial-load, as on the mainframe).
# Usage: scripts/online/transaction_curl_transcript.sh [base-url] > docs/validation/online/transaction-billpay-curl.md
# Seeds TRANSACT by running POSTTRAN in the app container (set SEED=0 to skip); tokens are redacted.
set -euo pipefail
BASE=${1:-http://localhost:${CARDDEMO_HTTP_PORT:-8080}}
API=$BASE/api/v1
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
COMPOSE=(docker compose -f "$ROOT/modernization/docker-compose.yml")
BODY=$(mktemp)
WORK=$(mktemp -d)
trap 'rm -rf "$BODY" "$WORK"' EXIT

# step <title> <curl args...>: prints the request (bearer redacted), status and pretty JSON; leaves the body in $BODY
step() {
  local title=$1; shift
  printf '### %s\n$ curl %s\n' "$title" "$(shown "$@")"
  local code
  code=$(curl -s -o "$BODY" -w '%{http_code}' "$@")
  printf 'HTTP %s\n' "$code"
  jq '(.. | objects | select(has("token")) | .token) |= "<redacted>"' "$BODY" 2>/dev/null || cat "$BODY"
  printf '\n'
}

shown() {
  local out=()
  for a in "$@"; do
    case $a in
      "Authorization: Bearer "*) out+=("'Authorization: Bearer \$TOKEN'") ;;
      *[[:space:]\"{}?\&]*) out+=("'$a'") ;;
      *) out+=("$a") ;;
    esac
  done
  printf '%s' "${out[*]}"
}

cat <<HDR
# Transaction list / view / add and bill payment — curl transcript (docker compose)

Generated by \`scripts/online/transaction_curl_transcript.sh\` against \`docker compose up -d --build --wait\` (local
profile, initial load of \`app/data/EBCDIC\`, fresh volume) on branch \`devin/unt51-20-transactions-billpay\`; tokens
redacted. TRANSACT is empty after the initial load, so the script first runs POSTTRAN (\`--job=posttran\`) in the app
container to post the 300 sample daily transactions. Steps: sign-on, list first / PF8 next / PF7 previous page,
non-numeric start id (400), row selection, detail, unknown id (404), add with validation failures (400), ENTER
(validate only), confirm Y (201, next id), PF5 copy-last, bill payment show / pay / zero-balance reject, and two
concurrent payments of one account with the same version (one 200, one 409).

\`\`\`text
HDR

step "Sign on as USER0001 (type U)" "$API/auth/login" -H 'Content-Type: application/json' \
  -d '{"userId":"USER0001","password":"PASSWORD"}'
TOKEN=$(jq -r .token "$BODY")
UA="Authorization: Bearer $TOKEN"
JSON='Content-Type: application/json'

if [ "${SEED:-1}" != 0 ]; then
  printf '### Seed TRANSACT: POSTTRAN in the app container\n'
  printf '$ docker compose exec carddemo-app java -jar /app/carddemo-app.jar --job=posttran --run-date=2022-07-06 ...\n'
  rc=0
  "${COMPOSE[@]}" exec -T carddemo-app java -jar /app/carddemo-app.jar --job=posttran --run-date=2022-07-06 \
    --STEP10.SYSOUT=/tmp/cbtrn01c.txt --STEP15.SYSOUT=/tmp/cbtrn02c.txt >"$WORK/posttran.log" 2>&1 || rc=$?
  grep -E "posttran (STEP|ended)" "$WORK/posttran.log" | sed 's/^.*INFO [^:]*: /  /' || true
  printf 'exit code %s\n\n' "$rc"
fi

step "CT00 first page (ENTER, blank start id: 10 rows in TRAN-ID order)" "$API/transactions?limit=10" -H "$UA"
NEXT=$(jq -r .nextPage "$BODY")
step "CT00 PF8 next page" "$API/transactions?after=$NEXT&page=1" -H "$UA"
PREV=$(jq -r .previousPage "$BODY")
step "CT00 PF7 previous page (back to page 1)" "$API/transactions?before=$PREV&page=2" -H "$UA"
FIRST=$(jq -r '.rows[0].tranId' "$BODY")
SECOND=$(jq -r '.rows[1].tranId' "$BODY")
step "CT00 non-numeric start id -> 400" "$API/transactions?startTranId=12AB" -H "$UA"
step "CT00 PF7 on page 1 -> already at the top" "$API/transactions?before=$FIRST&page=1" -H "$UA"
step "CT00 select row 2 with S (XCTL to COTRN01C)" -X POST "$API/transactions/selection" -H "$UA" -H "$JSON" \
  -d "{\"rows\":[{\"tranId\":\"$FIRST\",\"selection\":\"\"},{\"tranId\":\"$SECOND\",\"selection\":\"S\"}]}"
step "CT01 detail (full card number, as COTRN1A shows it)" "$API/transactions/$SECOND?fromProgram=COTRN00C" -H "$UA"
step "CT01 unknown id -> 404" "$API/transactions/9999999999999999" -H "$UA"

form() {
  jq -nc --arg acct "$1" --arg amount "$2" --arg confirm "$3" '{accountId:$acct, cardNumber:"", typeCode:"01",
    categoryCode:"0001", source:"POS TERM", description:"Online purchase", amount:$amount, origDate:"2022-07-06",
    procDate:"2022-07-06", merchantId:"000000001", merchantName:"Corner Store", merchantCity:"Seattle",
    merchantZip:"98101", confirm:$confirm}'
}
step "CT02 no account or card -> 400" -X POST "$API/transactions" -H "$UA" -H "$JSON" -d "$(form "" "+00000012.34" "")"
step "CT02 amount without sign -> 400" -X POST "$API/transactions" -H "$UA" -H "$JSON" -d "$(form 1 "12.34" "")"
step "CT02 invalid date -> 400" -X POST "$API/transactions" -H "$UA" -H "$JSON" \
  -d "$(form 1 "-00000012.34" "" | jq -c '.origDate = "2022-02-30"')"
step "CT02 ENTER (confirm blank) -> VALIDATED, nothing written" -X POST "$API/transactions" -H "$UA" -H "$JSON" \
  -d "$(form 1 "-00000012.34" "")"
step "CT02 confirm Y -> 201 ADDED, id = last + 1" -X POST "$API/transactions" -H "$UA" -H "$JSON" \
  -d "$(form 1 "-00000012.34" "Y")"
ADDED=$(jq -r .transaction.tranId "$BODY")
step "CT01 detail of the new transaction" "$API/transactions/$ADDED" -H "$UA"
step "CT02 PF5 copy last transaction (copyLast=true)" -X POST "$API/transactions" -H "$UA" -H "$JSON" \
  -d '{"accountId":"1","copyLast":true}'

pay() {
  step "$1" -X POST "$API/accounts/$2/bill-payment" -H "$UA" -H "$JSON" -d "$3"
}
pay "CB00 account 1 ENTER (show balance and version)" 1 '{"confirm":""}'
V=$(jq -r .version "$BODY")
pay "CB00 account 1 confirm Y -> PAID, balance 0" 1 "{\"confirm\":\"Y\",\"version\":$V}"
V=$(jq -r .version "$BODY")
pay "CB00 account 1 again -> 400 nothing to pay (balance 0)" 1 "{\"confirm\":\"Y\",\"version\":$V}"
pay "CB00 blank account id -> 400" "%20" '{"confirm":""}'
pay "CB00 account 2 ENTER" 2 '{"confirm":""}'
V=$(jq -r .version "$BODY")

printf '### CB00 account 2: two concurrent confirm Y with version %s\n' "$V"
printf '$ curl -X POST %s -d '"'"'{"confirm":"Y","version":%s}'"'"' &  (twice)\n' "$API/accounts/2/bill-payment" "$V"
for i in 1 2; do
  curl -s -o "$WORK/pay$i.json" -w '%{http_code}' -X POST "$API/accounts/2/bill-payment" -H "$UA" -H "$JSON" \
    -d "{\"confirm\":\"Y\",\"version\":$V}" >"$WORK/pay$i.code" &
done
wait
for i in $(for i in 1 2; do printf '%s %s\n' "$(cat "$WORK/pay$i.code")" "$i"; done | sort | cut -d' ' -f2); do
  printf 'HTTP %s\n' "$(cat "$WORK/pay$i.code")"
  jq . "$WORK/pay$i.json"
done
printf '\n'
step "CT00 PF7 from past the last id: the last page ends with the online rows" \
  "$API/transactions?before=9999999999999999&page=2" -H "$UA"

printf '```\n'
cat <<'FTR'

Not covered by this transcript (covered by tests instead): duplicate transaction id (409 `DUPREC`, WebMvc rules test
— cannot be provoked through the API because ids are assigned under the advisory lock), rollback when the account
update fails (`TransactionApiIT`), TRANREPT reporting online rows (`TransactionApiIT`), ADMIN sign-on (same
endpoints, no role difference in the COBOL).
FTR
