#!/usr/bin/env bash
# User administration (CU00..CU03) and transaction report (CR00) curl transcript against a running
# `docker compose up -d --build --wait` stack (fresh volume).
# Usage: scripts/online/user_report_curl_transcript.sh [base-url] > docs/validation/online/user-admin-reports-curl.md
# Seeds TRANSACT by running POSTTRAN in the app container (set SEED=0 to skip); tokens are redacted.
set -euo pipefail
BASE=${1:-http://localhost:${CARDDEMO_HTTP_PORT:-8080}}
API=$BASE/api/v1
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
COMPOSE=(docker compose -f "$ROOT/modernization/docker-compose.yml")
APP=(java -jar /app/carddemo-app.jar)
BODY=$(mktemp)
WORK=$(mktemp -d)
trap 'rm -rf "$BODY" "$WORK"' EXIT

# step <title> <curl args...>: prints the request (bearer redacted), status and pretty JSON; leaves the body in $BODY
step() {
  local title=$1; shift
  printf '### %s\n$ curl %s\n' "$title" "$(shown "$@")"
  local code
  code=$(curl -s -o "$BODY" -w '%{http_code}' "$@")
  printf 'HTTP %s\n' "$code"
  jq '(.. | objects | select(has("token")) | .token) |= "<redacted>"' "$BODY" 2>/dev/null || cat "$BODY"
  printf '\n'
}

shown() {
  local out=()
  for a in "$@"; do
    case $a in
      "Authorization: Bearer "*) out+=("'Authorization: Bearer \$TOKEN'") ;;
      *[[:space:]\"{}?\&]*) out+=("'$a'") ;;
      *) out+=("$a") ;;
    esac
  done
  printf '%s' "${out[*]}"
}

login() {
  curl -s "$API/auth/login" -H 'Content-Type: application/json' \
    -d "{\"userId\":\"$1\",\"password\":\"PASSWORD\"}" | jq -r .token
}

# poll <execution id>: GET the status until COMPLETED/FAILED; prints each state change and the final body
poll() {
  local last="" state
  printf '### Poll report execution %s until it finishes\n$ curl %s/reports/transactions/%s  (every 0.5 s)\n' \
    "$1" "$API" "$1"
  for _ in $(seq 1 240); do
    curl -s -o "$BODY" "$API/reports/transactions/$1" -H "$AA"
    state=$(jq -r .status "$BODY")
    [ "$state" != "$last" ] && printf 'status %s\n' "$state" && last=$state
    case $state in COMPLETED|FAILED) break ;; esac
    sleep 0.5
  done
  jq 'if .report then .report.lines |= (.[:4] + ["... (" + ((length - 4) | tostring) + " more lines)"]) else . end' \
    "$BODY"
  printf '\n'
}

cat <<HDR
# User administration and transaction report — curl transcript (docker compose)

Generated by \`scripts/online/user_report_curl_transcript.sh\` against \`docker compose up -d --build --wait\` (local
profile, initial load of \`app/data/EBCDIC\`, fresh volume) on branch \`devin/unt51-21-users-reports\`; tokens redacted.
USRSEC holds the 10 sample users after the initial load, so three users are added first to get a second page.\nPOSTTRAN stamps PROC-TS with the current time, so the posted rows fall in the Monthly / Yearly ranges and the 2022\nCustom range is empty (header-free empty report, as CBTRN03C writes nothing without a selected record).
Steps: USER token refused (403 NOTAUTH), add (201) and duplicate (409), list first / PF8 next / PF7 previous page,
selection U/D/invalid, update no-change / success / stale version (409), delete ENTER / N / Y, then report requests
Monthly (validate only, submit, poll to completion, download), Yearly, Custom (cancel, submit), invalid date, reversed
range, and the Monthly range run with \`--job=tranrept\` in the container: both TRANREPT files hash the same.

\`\`\`text
HDR

AT=$(login ADMIN001); AA="Authorization: Bearer $AT"
UT=$(login USER0001); UA="Authorization: Bearer $UT"
JSON='Content-Type: application/json'
printf '### Sign on ADMIN001 (type A) and USER0001 (type U): tokens in $TOKEN (redacted)\n\n'

step "CU00 with a USER token -> 403 NOTAUTH" "$API/users?limit=10" -H "$UA"
step "CU01 with a USER token -> 403 NOTAUTH" -X POST "$API/users" -H "$UA" -H "$JSON" -d '{}'
for id in ZUSER001 ZUSER002 ZUSER003; do
  step "CU01 add $id" -X POST "$API/users" -H "$AA" -H "$JSON" \
    -d "{\"firstName\":\"Zed\",\"lastName\":\"Test $id\",\"userId\":\"$id\",\"password\":\"ZPASS\",\"userType\":\"U\"}"
done
step "CU01 add duplicate ZUSER001 -> 409 User ID already exist..." -X POST "$API/users" -H "$AA" -H "$JSON" \
  -d '{"firstName":"Dup","lastName":"User","userId":"ZUSER001","password":"X","userType":"U"}'
step "CU01 missing last name -> 400" -X POST "$API/users" -H "$AA" -H "$JSON" \
  -d '{"firstName":"No","lastName":"","userId":"ZUSER009","password":"X","userType":"U"}'
step "CU01 user type X -> 400" -X POST "$API/users" -H "$AA" -H "$JSON" \
  -d '{"firstName":"No","lastName":"Type","userId":"ZUSER009","password":"X","userType":"X"}'

step "CU00 first page (10 rows in USRSEC key order)" "$API/users?limit=10" -H "$AA"
NEXT=$(jq -r .nextPage "$BODY")
step "CU00 PF8 next page" "$API/users?after=$NEXT&page=1&limit=10" -H "$AA"
PREV=$(jq -r .previousPage "$BODY")
step "CU00 PF8 again on the last page -> already at the bottom" "$API/users?after=ZUSER003&page=2&limit=10" -H "$AA"
step "CU00 PF7 previous page (back to page 1)" "$API/users?before=$PREV&page=2&limit=10" -H "$AA"
step "CU00 select ZUSER002 with U (XCTL to COUSR02C)" -X POST "$API/users/selection" -H "$AA" -H "$JSON" \
  -d '{"rows":[{"userId":"ZUSER001","selection":""},{"userId":"ZUSER002","selection":"U"}]}'
step "CU00 select with X -> 400 invalid selection" -X POST "$API/users/selection" -H "$AA" -H "$JSON" \
  -d '{"rows":[{"userId":"ZUSER001","selection":"X"}]}'

step "CU02 fetch ZUSER002" "$API/users/ZUSER002?fromProgram=COUSR00C" -H "$AA"
V=$(jq -r .user.version "$BODY")
step "CU02 PF5 with the same values -> Please modify to update ..." -X PUT "$API/users/ZUSER002" -H "$AA" -H "$JSON" \
  -d "{\"firstName\":\"Zed\",\"lastName\":\"Test ZUSER002\",\"password\":\"ZPASS\",\"userType\":\"U\",\"version\":$V}"
step "CU02 PF5 new password and type A -> updated" -X PUT "$API/users/ZUSER002" -H "$AA" -H "$JSON" \
  -d "{\"firstName\":\"Zed\",\"lastName\":\"Test ZUSER002\",\"password\":\"NEWPASS\",\"userType\":\"A\",\"version\":$V}"
step "CU02 PF5 again with the old version -> 409 CHANGED" -X PUT "$API/users/ZUSER002" -H "$AA" -H "$JSON" \
  -d "{\"firstName\":\"Zed\",\"lastName\":\"Stale\",\"password\":\"NEWPASS\",\"userType\":\"A\",\"version\":$V}"
step "CU02 unknown user -> 404" "$API/users/NOBODY" -H "$AA"

step "CU03 ENTER: show ZUSER003 and ask to confirm" -X DELETE "$API/users/ZUSER003?fromProgram=COUSR00C" -H "$AA"
V=$(jq -r .user.version "$BODY")
step "CU03 confirm N -> cancelled, nothing deleted" -X DELETE "$API/users/ZUSER003?confirm=N" -H "$AA"
step "CU03 confirm Y -> deleted" -X DELETE "$API/users/ZUSER003?confirm=Y&version=$V" -H "$AA"
step "CU02 ZUSER003 is gone -> 404" "$API/users/ZUSER003" -H "$AA"

if [ "${SEED:-1}" != 0 ]; then
  printf '### Seed TRANSACT: POSTTRAN in the app container\n'
  printf '$ docker compose exec carddemo-app java -jar /app/carddemo-app.jar --job=posttran --run-date=2022-07-06 ...\n'
  rc=0
  "${COMPOSE[@]}" exec -T carddemo-app "${APP[@]}" --job=posttran --run-date=2022-07-06 \
    --STEP10.SYSOUT=/tmp/cbtrn01c.txt --STEP15.SYSOUT=/tmp/cbtrn02c.txt >"$WORK/posttran.log" 2>&1 || rc=$?
  grep -E "posttran (STEP|ended)" "$WORK/posttran.log" | sed 's/^.*INFO [^:]*: /  /' || true
  printf 'exit code %s\n\n' "$rc"
fi

R=$API/reports/transactions
step "CR00 Monthly, blank confirm -> validate only (current month)" -X POST "$R" -H "$AA" -H "$JSON" \
  -d '{"reportType":"Monthly","confirm":""}'
step "CR00 Monthly confirm Y -> 202 queued" -X POST "$R" -H "$AA" -H "$JSON" -d '{"reportType":"Monthly","confirm":"Y"}'
ID=$(jq -r .executionId "$BODY")
START=$(jq -r .parmStartDate "$BODY")
END=$(jq -r .parmEndDate "$BODY")
poll "$ID"
step "CR00 Yearly confirm Y -> 202 queued" -X POST "$R" -H "$AA" -H "$JSON" -d '{"reportType":"Yearly","confirm":"Y"}'
poll "$(jq -r .executionId "$BODY")"
CUSTOM='"startDate":{"month":"01","day":"01","year":"2022"},"endDate":{"month":"07","day":"06","year":"2022"}'
step "CR00 Custom 2022-01-01..2022-07-06 confirm N -> cancelled" -X POST "$R" -H "$AA" -H "$JSON" \
  -d "{\"reportType\":\"Custom\",$CUSTOM,\"confirm\":\"N\"}"
step "CR00 Custom 2022-01-01..2022-07-06 confirm Y -> 202 queued" -X POST "$R" -H "$AA" -H "$JSON" \
  -d "{\"reportType\":\"Custom\",$CUSTOM,\"confirm\":\"Y\"}"
poll "$(jq -r .executionId "$BODY")"
step "CR00 Custom 2022-02-30 -> 400 Start Date - Not a valid date..." -X POST "$R" -H "$AA" -H "$JSON" \
  -d '{"reportType":"Custom","startDate":{"month":"02","day":"30","year":"2022"},"endDate":{"month":"07","day":"06","year":"2022"},"confirm":"Y"}'
step "CR00 Custom month 13 -> 400 Start Date - Not a valid Month..." -X POST "$R" -H "$AA" -H "$JSON" \
  -d '{"reportType":"Custom","startDate":{"month":"13","day":"01","year":"2022"},"endDate":{"month":"07","day":"06","year":"2022"},"confirm":"Y"}'
step "CR00 Custom reversed range -> 400 Start Date can NOT be after End Date..." -X POST "$R" -H "$AA" -H "$JSON" \
  -d '{"reportType":"Custom","startDate":{"month":"07","day":"06","year":"2022"},"endDate":{"month":"01","day":"01","year":"2022"},"confirm":"Y"}'
step "CR00 another user's execution -> 404" "$R/$ID" -H "$UA"

printf '### Online vs CLI: download Monthly execution %s, run --job=tranrept for the same range in the container\n' "$ID"
printf '$ curl -o online.TRANREPT %s/%s/report\n' "$R" "$ID"
curl -s -o "$WORK/online.TRANREPT" "$R/$ID/report" -H "$AA"
RUN_DATE=$(jq -r .runDate <(curl -s "$R/$ID" -H "$AA"))
printf '$ docker compose exec carddemo-app java -jar /app/carddemo-app.jar --job=tranrept --run-date=%s ' "$RUN_DATE"
printf -- "--PARM-START-DATE=%s --PARM-END-DATE=%s --STEP15.SYSOUT=/tmp/cbtrn03c.txt\n" "$START" "$END"
rc=0
"${COMPOSE[@]}" exec -T carddemo-app "${APP[@]}" --job=tranrept --run-date="$RUN_DATE" \
  --PARM-START-DATE="$START" --PARM-END-DATE="$END" --STEP15.SYSOUT=/tmp/cbtrn03c.txt \
  >"$WORK/tranrept.log" 2>&1 || rc=$?
grep -E "tranrept (STEP|ended)" "$WORK/tranrept.log" | sed 's/^.*INFO [^:]*: /  /' || true
printf 'exit code %s\n' "$rc"
CLI=$("${COMPOSE[@]}" exec -T postgres psql -U "${CARDDEMO_DB_USER:-carddemo}" -d "${CARDDEMO_DB_NAME:-carddemo}" -tA \
  -c "select file_path from batch_output_file where gdg_base = 'TRANREPT' order by output_file_id desc limit 1")
"${COMPOSE[@]}" exec -T carddemo-app cat "$CLI" >"$WORK/cli.TRANREPT"
printf 'online %s  %s bytes\n' "$(sha256sum <"$WORK/online.TRANREPT" | cut -d' ' -f1)" "$(wc -c <"$WORK/online.TRANREPT")"
printf 'cli    %s  %s bytes  (%s)\n' "$(sha256sum <"$WORK/cli.TRANREPT" | cut -d' ' -f1)" \
  "$(wc -c <"$WORK/cli.TRANREPT")" "$CLI"
if cmp -s "$WORK/online.TRANREPT" "$WORK/cli.TRANREPT"; then echo "IDENTICAL"; else echo "DIFFERENT"; fi

printf '```\n'
cat <<'FTR'

Not covered by this transcript (covered by tests instead): a full report queue (503 `NOSPACE`, `TransactionReportRulesTest`
R-19), report job failure (FAILED status), byte-for-byte equality for Monthly and Yearly against the CLI
(`TransactionReportApiIT`, fixed clock 2022-07-06), lookup/rewrite I/O errors (`User*RulesTest`).
FTR
