package com.carddemo.account;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

/**
 * JPA entity for table {@code account}. Account record (ACCTDATA KSDS, key ACCT-ID); read by
 * COACTVWC/COBIL00C/CBTRN02C, rewritten by COACTUPC, COBIL00C, CBTRN02C and CBACT04C. Field Javadocs carry the
 * CVACT01Y item names; {@link AccountRecord} is the fixed-width value.
 */
@Entity
@Table(name = "account")
public class Account {

    /** ACCT-ID PIC 9(11). */
    @Id
    @Column(name = "acct_id")
    private long acctId;

    /** ACCT-ACTIVE-STATUS PIC X(01). */
    @Column(name = "active_status")
    private AccountStatus activeStatus;

    /** ACCT-CURR-BAL PIC S9(10)V99. */
    @Column(name = "curr_bal", precision = 12, scale = 2)
    private BigDecimal currBal;

    /** ACCT-CREDIT-LIMIT PIC S9(10)V99. */
    @Column(name = "credit_limit", precision = 12, scale = 2)
    private BigDecimal creditLimit;

    /** ACCT-CASH-CREDIT-LIMIT PIC S9(10)V99. */
    @Column(name = "cash_credit_limit", precision = 12, scale = 2)
    private BigDecimal cashCreditLimit;

    /** ACCT-OPEN-DATE PIC X(10). */
    @Column(name = "open_date")
    private String openDate;

    /** {@code open_date_dt}: ACCT-OPEN-DATE as a DATE, generated by the database. */
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "open_date_dt", insertable = false, updatable = false)
    private LocalDate openDateDt;

    /** ACCT-EXPIRAION-DATE PIC X(10). */
    @Column(name = "expiration_date")
    private String expirationDate;

    /** {@code expiration_date_dt}: ACCT-EXPIRAION-DATE as a DATE, generated by the database. */
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "expiration_date_dt", insertable = false, updatable = false)
    private LocalDate expirationDateDt;

    /** ACCT-REISSUE-DATE PIC X(10). */
    @Column(name = "reissue_date")
    private String reissueDate;

    /** {@code reissue_date_dt}: ACCT-REISSUE-DATE as a DATE, generated by the database. */
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "reissue_date_dt", insertable = false, updatable = false)
    private LocalDate reissueDateDt;

    /** ACCT-CURR-CYC-CREDIT PIC S9(10)V99. */
    @Column(name = "curr_cyc_credit", precision = 12, scale = 2)
    private BigDecimal currCycCredit;

    /** ACCT-CURR-CYC-DEBIT PIC S9(10)V99. */
    @Column(name = "curr_cyc_debit", precision = 12, scale = 2)
    private BigDecimal currCycDebit;

    /** ACCT-ADDR-ZIP PIC X(10). */
    @Column(name = "addr_zip")
    private String addrZip;

    /** ACCT-GROUP-ID PIC X(10). */
    @Column(name = "group_id")
    private String groupId;

    /** Optimistic-lock version (ADR-0010); not part of the VSAM record. */
    @Version
    @Column(name = "version")
    private long version;

    protected Account() {
    }

    public static Account from(AccountRecord record) {
        Account entity = new Account();
        entity.acctId = record.acctId();
        entity.activeStatus = record.activeStatus();
        entity.currBal = record.currBal();
        entity.creditLimit = record.creditLimit();
        entity.cashCreditLimit = record.cashCreditLimit();
        entity.openDate = record.openDate();
        entity.expirationDate = record.expirationDate();
        entity.reissueDate = record.reissueDate();
        entity.currCycCredit = record.currCycCredit();
        entity.currCycDebit = record.currCycDebit();
        entity.addrZip = record.addrZip();
        entity.groupId = record.groupId();
        return entity;
    }

    public AccountRecord toRecord() {
        return new AccountRecord(acctId, activeStatus, currBal, creditLimit, cashCreditLimit, openDate,
                expirationDate, reissueDate, currCycCredit, currCycDebit, addrZip, groupId);
    }

    /** {@code REWRITE}: replaces every non-key field with the values of {@code record}; the key must match. */
    public void update(AccountRecord record) {
        if (acctId != record.acctId()) {
            throw new IllegalArgumentException("account: cannot change the key of " + acctId + " via update");
        }
        this.activeStatus = record.activeStatus();
        this.currBal = record.currBal();
        this.creditLimit = record.creditLimit();
        this.cashCreditLimit = record.cashCreditLimit();
        this.openDate = record.openDate();
        this.expirationDate = record.expirationDate();
        this.reissueDate = record.reissueDate();
        this.currCycCredit = record.currCycCredit();
        this.currCycDebit = record.currCycDebit();
        this.addrZip = record.addrZip();
        this.groupId = record.groupId();
    }

    public long getAcctId() {
        return acctId;
    }

    public AccountStatus getActiveStatus() {
        return activeStatus;
    }

    public BigDecimal getCurrBal() {
        return currBal;
    }

    public BigDecimal getCreditLimit() {
        return creditLimit;
    }

    public BigDecimal getCashCreditLimit() {
        return cashCreditLimit;
    }

    public String getOpenDate() {
        return openDate;
    }

    /** ACCT-OPEN-DATE parsed by {@code cobol_iso_date}; read-only, the text is the source of truth. */
    public LocalDate getOpenDateDt() {
        return openDateDt;
    }

    public String getExpirationDate() {
        return expirationDate;
    }

    /** ACCT-EXPIRAION-DATE parsed by {@code cobol_iso_date}; read-only, the text is the source of truth. */
    public LocalDate getExpirationDateDt() {
        return expirationDateDt;
    }

    public String getReissueDate() {
        return reissueDate;
    }

    /** ACCT-REISSUE-DATE parsed by {@code cobol_iso_date}; read-only, the text is the source of truth. */
    public LocalDate getReissueDateDt() {
        return reissueDateDt;
    }

    public BigDecimal getCurrCycCredit() {
        return currCycCredit;
    }

    public BigDecimal getCurrCycDebit() {
        return currCycDebit;
    }

    public String getAddrZip() {
        return addrZip;
    }

    public String getGroupId() {
        return groupId;
    }

    public long getVersion() {
        return version;
    }
}
