package com.carddemo.interestcalc.parity;

import static org.assertj.core.api.Assertions.assertThat;

import com.carddemo.interestcalc.copybook.TransactionRecord;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;
import java.util.regex.Pattern;

/**
 * Support for the golden-master differential harness.
 *
 * <p>The golden files under {@code src/test/resources/golden} were produced by compiling the
 * unmodified {@code app/cbl/CBACT04C.cbl} with GnuCOBOL and running it against the datasets -
 * see {@code oracle/run-cobol-oracle.sh} and the README. They are a genuine oracle, not a
 * transcription of what this Java code happens to produce.
 */
public final class GoldenMaster {

    /** The PARM of {@code //STEP15 EXEC PGM=CBACT04C,PARM='2022071800'} in app/jcl/INTCALC.jcl. */
    public static final String RUN_DATE = "2022071800";

    /** Pinned {@code FUNCTION CURRENT-DATE}, so TRAN-ORIG-TS / TRAN-PROC-TS are deterministic. */
    public static final Clock FIXED_CLOCK =
            Clock.fixed(Instant.parse("2022-07-18T04:30:15.160Z"), ZoneOffset.UTC);

    public static final String EXPECTED_TIMESTAMP = "2022-07-18-04.30.15.160000";

    /** {@code YYYY-MM-DD-HH.MM.SS.MM0000} - the 26 character DB2 timestamp of Z-GET-DB2-FORMAT-TIMESTAMP. */
    public static final Pattern DB2_TIMESTAMP =
            Pattern.compile("\\d{4}-\\d{2}-\\d{2}-\\d{2}\\.\\d{2}\\.\\d{2}\\.\\d{2}0000");

    private GoldenMaster() {
    }

    /** Locates the repository root by walking up from the module directory. */
    public static Path repositoryRoot() {
        Path candidate = Path.of("").toAbsolutePath();
        while (candidate != null && !Files.isDirectory(candidate.resolve("app").resolve("cbl"))) {
            candidate = candidate.getParent();
        }
        if (candidate == null) {
            throw new IllegalStateException("cannot locate the CardDemo repository root from " + Path.of("").toAbsolutePath());
        }
        return candidate;
    }

    /** The legacy sample datasets, read in place from {@code app/data/ASCII}. */
    public static Path shippedDataset() {
        return repositoryRoot().resolve("app/data/ASCII");
    }

    /** The synthetic decimal edge-case dataset, generated by {@code oracle/make-edge-dataset.py}. */
    public static Path edgeDataset() {
        return repositoryRoot().resolve("modernized/interest-calculator/oracle/datasets/edge");
    }

    public static List<String> goldenLines(String resource) {
        try (InputStream in = GoldenMaster.class.getResourceAsStream("/golden/" + resource)) {
            assertThat(in).as("golden resource /golden/%s", resource).isNotNull();
            return new String(in.readAllBytes(), StandardCharsets.ISO_8859_1).lines().toList();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    public static List<TransactionRecord> goldenTransactions(String dataset) {
        return goldenLines(dataset + "/transact.dat").stream().map(TransactionRecord::parse).toList();
    }

    /**
     * Every field of {@code TRAN-RECORD} except the two timestamps, which are the job's only
     * nondeterministic outputs and are asserted separately.
     */
    public static List<NamedField> comparableFields(TransactionRecord source) {
        // Compare the fields as they appear in the 350 byte record image, so that a value the
        // Java side holds unpadded ("System") is compared against the COBOL field it lands in
        // ("System    ").
        TransactionRecord record = TransactionRecord.parse(source.format());
        List<NamedField> fields = new ArrayList<>();
        add(fields, "TRAN-ID", record, TransactionRecord::transactionId);
        add(fields, "TRAN-TYPE-CD", record, TransactionRecord::typeCode);
        add(fields, "TRAN-CAT-CD", record, TransactionRecord::categoryCode);
        add(fields, "TRAN-SOURCE", record, TransactionRecord::source);
        add(fields, "TRAN-DESC", record, TransactionRecord::description);
        fields.add(new NamedField("TRAN-AMT", record.amount().toPlainString()));
        add(fields, "TRAN-MERCHANT-ID", record, TransactionRecord::merchantId);
        add(fields, "TRAN-MERCHANT-NAME", record, TransactionRecord::merchantName);
        add(fields, "TRAN-MERCHANT-CITY", record, TransactionRecord::merchantCity);
        add(fields, "TRAN-MERCHANT-ZIP", record, TransactionRecord::merchantZip);
        add(fields, "TRAN-CARD-NUM", record, TransactionRecord::cardNumber);
        return fields;
    }

    private static void add(List<NamedField> fields, String name, TransactionRecord record,
                            Function<TransactionRecord, String> accessor) {
        fields.add(new NamedField(name, accessor.apply(record)));
    }

    public record NamedField(String name, String value) {
    }
}
