flowchart LR
    classDef high fill:#f8d7da,stroke:#c00;
    classDef medium fill:#fff3cd,stroke:#c90;
    classDef low fill:#d4edda,stroke:#090;
    classDef ext fill:#eee,stroke:#999,stroke-dasharray: 3 3;
    classDef ds fill:#e7f0ff,stroke:#36c;
    classDef job fill:#f3e8ff,stroke:#63c;
    COACTUPC["COACTUPC"]
    class COACTUPC high;
    COACTVWC["COACTVWC"]
    class COACTVWC medium;
    COBIL00C["COBIL00C"]
    class COBIL00C medium;
    COCRDLIC["COCRDLIC"]
    class COCRDLIC high;
    COCRDSLC["COCRDSLC"]
    class COCRDSLC medium;
    COCRDUPC["COCRDUPC"]
    class COCRDUPC high;
    COSGN00C["COSGN00C"]
    class COSGN00C low;
    COTRN00C["COTRN00C"]
    class COTRN00C medium;
    COTRN01C["COTRN01C"]
    class COTRN01C low;
    COTRN02C["COTRN02C"]
    class COTRN02C medium;
    COUSR00C["COUSR00C"]
    class COUSR00C medium;
    COUSR01C["COUSR01C"]
    class COUSR01C low;
    COUSR02C["COUSR02C"]
    class COUSR02C low;
    COUSR03C["COUSR03C"]
    class COUSR03C low;
    F_CXACAIX[("CXACAIX<br/>AWS.M2.CARDDEMO.CARDXREF.VSAM.AIX.PATH")]
    class F_CXACAIX ds;
    F_ACCTDAT[("ACCTDAT<br/>AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS")]
    class F_ACCTDAT ds;
    F_CUSTDAT[("CUSTDAT<br/>AWS.M2.CARDDEMO.CUSTDATA.VSAM.KSDS")]
    class F_CUSTDAT ds;
    F_TRANSACT[("TRANSACT<br/>AWS.M2.CARDDEMO.TRANSACT.VSAM.KSDS")]
    class F_TRANSACT ds;
    F_CARDDAT[("CARDDAT<br/>AWS.M2.CARDDEMO.CARDDATA.VSAM.KSDS")]
    class F_CARDDAT ds;
    F_CARDAIX[("CARDAIX<br/>AWS.M2.CARDDEMO.CARDDATA.VSAM.AIX.PATH")]
    class F_CARDAIX ds;
    F_USRSEC[("USRSEC<br/>AWS.M2.CARDDEMO.USRSEC.VSAM.KSDS")]
    class F_USRSEC ds;
    F_CCXREF[("CCXREF<br/>AWS.M2.CARDDEMO.CARDXREF.VSAM.KSDS")]
    class F_CCXREF ds;
    COACTUPC -->|"RANDOM/R: READ"| F_CXACAIX
    COACTUPC -->|"RANDOM/RW: READ REWRITE"| F_ACCTDAT
    COACTUPC -->|"RANDOM/RW: READ REWRITE"| F_CUSTDAT
    COACTVWC -->|"RANDOM/R: READ"| F_CXACAIX
    COACTVWC -->|"RANDOM/R: READ"| F_ACCTDAT
    COACTVWC -->|"RANDOM/R: READ"| F_CUSTDAT
    COBIL00C -->|"RANDOM/RW: READ REWRITE"| F_ACCTDAT
    COBIL00C -->|"RANDOM/R: READ"| F_CXACAIX
    COBIL00C -->|"BROWSE/RW: STARTBR READPREV ENDBR WRITE"| F_TRANSACT
    COCRDLIC -->|"BROWSE/R: STARTBR READNEXT ENDBR READPREV"| F_CARDDAT
    COCRDSLC -->|"RANDOM/R: READ"| F_CARDDAT
    COCRDSLC -->|"RANDOM/R: READ"| F_CARDAIX
    COCRDUPC -->|"RANDOM/RW: READ REWRITE"| F_CARDDAT
    COSGN00C -->|"RANDOM/R: READ"| F_USRSEC
    COTRN00C -->|"BROWSE/R: STARTBR READNEXT READPREV ENDBR"| F_TRANSACT
    COTRN01C -->|"RANDOM/R: READ"| F_TRANSACT
    COTRN02C -->|"RANDOM/R: READ"| F_CXACAIX
    COTRN02C -->|"RANDOM/R: READ"| F_CCXREF
    COTRN02C -->|"BROWSE/RW: STARTBR READPREV ENDBR WRITE"| F_TRANSACT
    COUSR00C -->|"BROWSE/R: STARTBR READNEXT READPREV ENDBR"| F_USRSEC
    COUSR01C -->|"RANDOM/W: WRITE"| F_USRSEC
    COUSR02C -->|"RANDOM/RW: READ REWRITE"| F_USRSEC
    COUSR03C -->|"RANDOM/RW: READ DELETE"| F_USRSEC
