/**
 * Build time generator: parses every `.bms` map in `app/bms` and writes the
 * typed screen definitions under `src/generated`. The output is committed, so
 * the package builds without the COBOL sources; re-run `npm run generate` in
 * this package when a map changes.
 */

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseBms } from "../src/bms/parser.js";
import type { ScreenDefinition } from "../src/bms/types.js";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const bmsDirectory = resolve(packageRoot, "../../../app/bms");
const outputDirectory = join(packageRoot, "src/generated");

const HEADER = (mapset: string): string =>
  [
    `// Generated from app/bms/${mapset}.bms by scripts/generate-screens.ts.`,
    "// Do not edit by hand; run `npm run generate` instead.",
    "",
    'import type { ScreenDefinition } from "../bms/types.js";',
    "",
  ].join("\n");

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Emits an object literal with unquoted keys, matching the hand written source. */
function render(value: unknown, indent = ""): string {
  if (Array.isArray(value)) {
    const items = value.map((item) => `${indent}  ${render(item, `${indent}  `)},`);
    return items.length === 0 ? "[]" : `[\n${items.join("\n")}\n${indent}]`;
  }
  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value).map(([key, item]) => {
      const name = IDENTIFIER.test(key) ? key : JSON.stringify(key);
      return `${indent}  ${name}: ${render(item, `${indent}  `)},`;
    });
    return entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n${indent}}`;
  }
  return JSON.stringify(value);
}

function renderScreen(screen: ScreenDefinition): string {
  return `export const ${screen.map}: ScreenDefinition = ${render(screen)};\n`;
}

function generate(): void {
  rmSync(outputDirectory, { recursive: true, force: true });
  mkdirSync(outputDirectory, { recursive: true });

  const sources = readdirSync(bmsDirectory)
    .filter((file) => file.endsWith(".bms"))
    .sort();
  const screens: ScreenDefinition[] = [];

  for (const file of sources) {
    const mapset = parseBms(readFileSync(join(bmsDirectory, file), "latin1"));
    const body = mapset.maps.map(renderScreen).join("\n");
    writeFileSync(join(outputDirectory, `${mapset.name.toLowerCase()}.ts`), `${HEADER(mapset.name)}\n${body}`);
    screens.push(...mapset.maps);
  }

  const imports = screens
    .map((screen) => `import { ${screen.map} } from "./${screen.mapset.toLowerCase()}.js";`)
    .join("\n");
  const byMap = screens.map((screen) => `  ${screen.map},`).join("\n");
  const byMapset = screens.map((screen) => `  ${screen.mapset}: ${screen.map},`).join("\n");

  const index = [
    "// Generated by scripts/generate-screens.ts. Do not edit by hand.",
    "",
    'import type { ScreenDefinition } from "../bms/types.js";',
    imports,
    "",
    screens.map((screen) => `export { ${screen.map} } from "./${screen.mapset.toLowerCase()}.js";`).join("\n"),
    "",
    "/** Every generated map, keyed by its `DFHMDI` name. */",
    "export const SCREENS_BY_MAP: Readonly<Record<string, ScreenDefinition>> = {",
    byMap,
    "};",
    "",
    "/** Every generated map, keyed by its `DFHMSD` mapset name. */",
    "export const SCREENS_BY_MAPSET: Readonly<Record<string, ScreenDefinition>> = {",
    byMapset,
    "};",
    "",
  ].join("\n");

  writeFileSync(join(outputDirectory, "index.ts"), index);
  process.stdout.write(`generated ${String(screens.length)} screens from ${String(sources.length)} maps\n`);
}

generate();
