package com.carddemo.customer;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.LocalDate;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

/**
 * JPA entity for table {@code customer}. Customer record (CUSTDATA KSDS, key CUST-ID); read by COACTVWC, rewritten
 * by COACTUPC. Field Javadocs carry the CVCUS01Y item names; {@link CustomerRecord} is the fixed-width value.
 */
@Entity
@Table(name = "customer")
public class Customer {

    /** CUST-ID PIC 9(09). */
    @Id
    @Column(name = "cust_id")
    private int custId;

    /** CUST-FIRST-NAME PIC X(25). */
    @Column(name = "first_name")
    private String firstName;

    /** CUST-MIDDLE-NAME PIC X(25). */
    @Column(name = "middle_name")
    private String middleName;

    /** CUST-LAST-NAME PIC X(25). */
    @Column(name = "last_name")
    private String lastName;

    /** CUST-ADDR-LINE-1 PIC X(50). */
    @Column(name = "addr_line_1")
    private String addrLine1;

    /** CUST-ADDR-LINE-2 PIC X(50). */
    @Column(name = "addr_line_2")
    private String addrLine2;

    /** CUST-ADDR-LINE-3 PIC X(50). */
    @Column(name = "addr_line_3")
    private String addrLine3;

    /** CUST-ADDR-STATE-CD PIC X(02). */
    @Column(name = "addr_state_cd")
    private String addrStateCd;

    /** CUST-ADDR-COUNTRY-CD PIC X(03). */
    @Column(name = "addr_country_cd")
    private String addrCountryCd;

    /** CUST-ADDR-ZIP PIC X(10). */
    @Column(name = "addr_zip")
    private String addrZip;

    /** CUST-PHONE-NUM-1 PIC X(15). */
    @Column(name = "phone_num_1")
    private String phoneNum1;

    /** CUST-PHONE-NUM-2 PIC X(15). */
    @Column(name = "phone_num_2")
    private String phoneNum2;

    /** CUST-SSN PIC 9(09). */
    @Column(name = "ssn")
    private int ssn;

    /** CUST-GOVT-ISSUED-ID PIC X(20). */
    @Column(name = "govt_issued_id")
    private String govtIssuedId;

    /** CUST-DOB-YYYY-MM-DD PIC X(10). */
    @Column(name = "dob")
    private String dob;

    /** {@code dob_dt}: CUST-DOB-YYYY-MM-DD as a DATE, generated by the database. */
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "dob_dt", insertable = false, updatable = false)
    private LocalDate dobDt;

    /** CUST-EFT-ACCOUNT-ID PIC X(10). */
    @Column(name = "eft_account_id")
    private String eftAccountId;

    /** CUST-PRI-CARD-HOLDER-IND PIC X(01). */
    @Column(name = "pri_card_holder_ind")
    private PrimaryCardHolder priCardHolderInd;

    /** CUST-FICO-CREDIT-SCORE PIC 9(03). */
    @Column(name = "fico_credit_score")
    private int ficoCreditScore;

    /** Optimistic-lock version (ADR-0010); not part of the VSAM record. */
    @Version
    @Column(name = "version")
    private long version;

    protected Customer() {
    }

    public static Customer from(CustomerRecord record) {
        Customer entity = new Customer();
        entity.custId = record.custId();
        entity.firstName = record.firstName();
        entity.middleName = record.middleName();
        entity.lastName = record.lastName();
        entity.addrLine1 = record.addrLine1();
        entity.addrLine2 = record.addrLine2();
        entity.addrLine3 = record.addrLine3();
        entity.addrStateCd = record.addrStateCd();
        entity.addrCountryCd = record.addrCountryCd();
        entity.addrZip = record.addrZip();
        entity.phoneNum1 = record.phoneNum1();
        entity.phoneNum2 = record.phoneNum2();
        entity.ssn = record.ssn();
        entity.govtIssuedId = record.govtIssuedId();
        entity.dob = record.dob();
        entity.eftAccountId = record.eftAccountId();
        entity.priCardHolderInd = record.priCardHolderInd();
        entity.ficoCreditScore = record.ficoCreditScore();
        return entity;
    }

    public CustomerRecord toRecord() {
        return new CustomerRecord(custId, firstName, middleName, lastName, addrLine1, addrLine2, addrLine3,
                addrStateCd, addrCountryCd, addrZip, phoneNum1, phoneNum2, ssn, govtIssuedId, dob, eftAccountId,
                priCardHolderInd, ficoCreditScore);
    }

    /** {@code REWRITE}: replaces every non-key field with the values of {@code record}; the key must match. */
    public void update(CustomerRecord record) {
        if (custId != record.custId()) {
            throw new IllegalArgumentException("customer: cannot change the key of " + custId + " via update");
        }
        this.firstName = record.firstName();
        this.middleName = record.middleName();
        this.lastName = record.lastName();
        this.addrLine1 = record.addrLine1();
        this.addrLine2 = record.addrLine2();
        this.addrLine3 = record.addrLine3();
        this.addrStateCd = record.addrStateCd();
        this.addrCountryCd = record.addrCountryCd();
        this.addrZip = record.addrZip();
        this.phoneNum1 = record.phoneNum1();
        this.phoneNum2 = record.phoneNum2();
        this.ssn = record.ssn();
        this.govtIssuedId = record.govtIssuedId();
        this.dob = record.dob();
        this.eftAccountId = record.eftAccountId();
        this.priCardHolderInd = record.priCardHolderInd();
        this.ficoCreditScore = record.ficoCreditScore();
    }

    public int getCustId() {
        return custId;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getAddrLine1() {
        return addrLine1;
    }

    public String getAddrLine2() {
        return addrLine2;
    }

    public String getAddrLine3() {
        return addrLine3;
    }

    public String getAddrStateCd() {
        return addrStateCd;
    }

    public String getAddrCountryCd() {
        return addrCountryCd;
    }

    public String getAddrZip() {
        return addrZip;
    }

    public String getPhoneNum1() {
        return phoneNum1;
    }

    public String getPhoneNum2() {
        return phoneNum2;
    }

    public int getSsn() {
        return ssn;
    }

    public String getGovtIssuedId() {
        return govtIssuedId;
    }

    public String getDob() {
        return dob;
    }

    /** CUST-DOB-YYYY-MM-DD parsed by {@code cobol_iso_date}; read-only, the text is the source of truth. */
    public LocalDate getDobDt() {
        return dobDt;
    }

    public String getEftAccountId() {
        return eftAccountId;
    }

    public PrimaryCardHolder getPriCardHolderInd() {
        return priCardHolderInd;
    }

    public int getFicoCreditScore() {
        return ficoCreditScore;
    }

    public long getVersion() {
        return version;
    }
}
